//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoCP
    {
        public int MaSo { get; set; }
        public string SoHieu { get; set; }
        public Nullable<short> CoCon { get; set; }
        public Nullable<int> MaCha { get; set; }
        public Nullable<short> Cap { get; set; }
        public string Ten { get; set; }
        public Nullable<double> Kq1 { get; set; }
        public Nullable<double> Kq2 { get; set; }
        public Nullable<double> Kq3 { get; set; }
        public Nullable<double> Kq4 { get; set; }
        public Nullable<double> Kq5 { get; set; }
        public Nullable<double> Kq6 { get; set; }
        public Nullable<int> BC_ID { get; set; }
        public Nullable<System.DateTime> Ngay1 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<double> Kq7 { get; set; }
        public Nullable<double> Kq8 { get; set; }
        public Nullable<int> MK { get; set; }
    }
}
