//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKNhomP
    {
        public int MaSo { get; set; }
        public Nullable<int> MaCT { get; set; }
        public string SoHieu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string DienGiai { get; set; }
        public Nullable<double> SoPSNo { get; set; }
        public Nullable<double> SoPSCo { get; set; }
        public string ShDU { get; set; }
        public string ShTK { get; set; }
        public Nullable<double> SoPS2No { get; set; }
        public Nullable<double> SoPS2Co { get; set; }
        public Nullable<System.DateTime> NgayGS { get; set; }
        public string ShVT { get; set; }
    }
}
