//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdts48
    {
        public int MaSo { get; set; }
        public Nullable<short> TaiSan { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> MaTk1 { get; set; }
        public Nullable<int> MaTk2 { get; set; }
        public Nullable<double> MaTk3 { get; set; }
        public Nullable<double> DauNam { get; set; }
        public Nullable<double> CuoiKy { get; set; }
        public Nullable<short> NhomCha { get; set; }
        public Nullable<short> CoChiTiet { get; set; }
        public string DienGiaiE { get; set; }
        public string shtk1 { get; set; }
        public string shtk2 { get; set; }
        public string shtk3 { get; set; }
        public string shtk4 { get; set; }
        public string shtk5 { get; set; }
        public string shtk6 { get; set; }
        public string shtk7 { get; set; }
        public string shtk8 { get; set; }
        public string shtk9 { get; set; }
        public string shtk10 { get; set; }
    }
}
