//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungTu
    {
        public int MaSo { get; set; }
        public Nullable<int> MaCT { get; set; }
        public Nullable<short> MaLoai { get; set; }
        public Nullable<short> ThangCT { get; set; }
        public string SoHieu { get; set; }
        public Nullable<System.DateTime> NgayCT { get; set; }
        public Nullable<System.DateTime> NgayGS { get; set; }
        public Nullable<System.DateTime> NgayTL { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> MaKho { get; set; }
        public Nullable<int> MaNguon { get; set; }
        public Nullable<int> MaTKNo { get; set; }
        public Nullable<int> MaTKCo { get; set; }
        public Nullable<double> SoPS { get; set; }
        public Nullable<double> SoPS2No { get; set; }
        public Nullable<double> SoPS2Co { get; set; }
        public Nullable<int> MaTKTCNo { get; set; }
        public Nullable<int> MaTKTCCo { get; set; }
        public Nullable<int> MaVattu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> CT_ID { get; set; }
        public Nullable<double> SoXuat { get; set; }
        public Nullable<int> MaDT { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> CTGS { get; set; }
        public Nullable<int> MaKHC { get; set; }
        public Nullable<int> MaTP { get; set; }
        public Nullable<short> DVT { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string DienGiaiE { get; set; }
        public Nullable<double> TyGia { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<short> HanTT { get; set; }
        public string SH1 { get; set; }
        public Nullable<short> T1 { get; set; }
        public Nullable<double> TLCK { get; set; }
        public Nullable<double> CK { get; set; }
        public Nullable<int> MaDT1 { get; set; }
        public Nullable<int> MaDT2 { get; set; }
        public Nullable<int> MaDT3 { get; set; }
        public Nullable<short> XuLy { get; set; }
        public string MauSoHD { get; set; }
        public string LoaiHoaDon { get; set; }
        public string Nguoimuahang { get; set; }
        public string hinhthucthanhtoan { get; set; }
        public string sophieudathang { get; set; }
        public string chondiengiai { get; set; }
        public string phantramchietkhau { get; set; }
        public string sotienchietkhau { get; set; }
        public string solo { get; set; }
        public Nullable<System.DateTime> handung { get; set; }
        public Nullable<double> SoPSGoc { get; set; }
        public Nullable<double> nhanban { get; set; }
        public Nullable<System.DateTime> NgayImport { get; set; }
    }
}
