//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNDauNam
    {
        public int MaSo { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<double> DuNo_0 { get; set; }
        public Nullable<double> DuCo_0 { get; set; }
        public Nullable<double> DuNT_0 { get; set; }
        public Nullable<double> SoXuat { get; set; }
        public Nullable<short> HanTT { get; set; }
    }
}
