//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPGVHD
    {
        public int MaSo { get; set; }
        public Nullable<int> MaDT { get; set; }
        public Nullable<int> MaVattu { get; set; }
        public Nullable<double> CP1 { get; set; }
        public Nullable<double> CP2 { get; set; }
        public Nullable<double> CP3 { get; set; }
        public Nullable<double> CP4 { get; set; }
        public Nullable<double> TT2 { get; set; }
        public Nullable<double> TNK { get; set; }
        public Nullable<double> TyGia1 { get; set; }
        public Nullable<double> SL { get; set; }
        public Nullable<double> TT { get; set; }
        public string PN { get; set; }
        public Nullable<int> MaDT1 { get; set; }
        public Nullable<int> MaDT2 { get; set; }
        public Nullable<int> MaDT3 { get; set; }
    }
}
