//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKetChuyen
    {
        public int MaSo { get; set; }
        public Nullable<short> STT { get; set; }
        public string DienGiai { get; set; }
        public string TK1 { get; set; }
        public string TK2 { get; set; }
    }
}
