//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTaiSan
    {
        public int MaSo { get; set; }
        public Nullable<int> MaCTKT { get; set; }
        public string SoHieu { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<System.DateTime> VaoSo { get; set; }
        public Nullable<System.DateTime> NgayGhi { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> MaTS { get; set; }
        public Nullable<double> NG_NS { get; set; }
        public Nullable<double> NG_TBS { get; set; }
        public Nullable<double> NG_CNK { get; set; }
        public Nullable<double> NG_TD { get; set; }
        public Nullable<double> CL_NS { get; set; }
        public Nullable<double> CL_TBS { get; set; }
        public Nullable<double> CL_CNK { get; set; }
        public Nullable<double> CL_TD { get; set; }
        public string DienGiaiE { get; set; }
        public Nullable<double> taisanIdCu { get; set; }
    }
}
