//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachVatTu
    {
        public int mavattu { get; set; }
        public string SOHIEU { get; set; }
        public string TenVattu { get; set; }
        public string solo { get; set; }
        public Nullable<System.DateTime> Handung { get; set; }
        public Nullable<double> soluongnhap { get; set; }
        public Nullable<double> soluongxuat { get; set; }
        public Nullable<double> conlai { get; set; }
    }
}
