//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhMuc
    {
        public int MaSo { get; set; }
        public Nullable<int> MaTP { get; set; }
        public Nullable<int> MaNVL { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<short> ThangHL { get; set; }
    }
}
