//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoituongCT
    {
        public int MaSo { get; set; }
        public string DienGiai { get; set; }
        public string SoHieu { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<double> TriGia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTH { get; set; }
    }
}
