//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeThongTK
    {
        public int MaSo { get; set; }
        public string SoHieu { get; set; }
        public Nullable<short> Cap { get; set; }
        public string Ten { get; set; }
        public Nullable<short> Kieu { get; set; }
        public Nullable<short> Loai { get; set; }
        public Nullable<short> TKCon { get; set; }
        public Nullable<int> MaNT { get; set; }
        public Nullable<double> DuNo_0 { get; set; }
        public Nullable<double> DuCo_0 { get; set; }
        public Nullable<double> DuNT_0 { get; set; }
        public Nullable<double> No_1 { get; set; }
        public Nullable<double> Co_1 { get; set; }
        public Nullable<double> No_1_NT { get; set; }
        public Nullable<double> Co_1_NT { get; set; }
        public Nullable<double> DuNo_1 { get; set; }
        public Nullable<double> DuCo_1 { get; set; }
        public Nullable<double> DuNT_1 { get; set; }
        public Nullable<double> No_2 { get; set; }
        public Nullable<double> Co_2 { get; set; }
        public Nullable<double> No_2_NT { get; set; }
        public Nullable<double> Co_2_NT { get; set; }
        public Nullable<double> DuNo_2 { get; set; }
        public Nullable<double> DuCo_2 { get; set; }
        public Nullable<double> DuNT_2 { get; set; }
        public Nullable<double> No_3 { get; set; }
        public Nullable<double> Co_3 { get; set; }
        public Nullable<double> No_3_NT { get; set; }
        public Nullable<double> Co_3_NT { get; set; }
        public Nullable<double> DuNo_3 { get; set; }
        public Nullable<double> DuCo_3 { get; set; }
        public Nullable<double> DuNT_3 { get; set; }
        public Nullable<double> No_4 { get; set; }
        public Nullable<double> Co_4 { get; set; }
        public Nullable<double> No_4_NT { get; set; }
        public Nullable<double> Co_4_NT { get; set; }
        public Nullable<double> DuNo_4 { get; set; }
        public Nullable<double> DuCo_4 { get; set; }
        public Nullable<double> DuNT_4 { get; set; }
        public Nullable<double> No_5 { get; set; }
        public Nullable<double> Co_5 { get; set; }
        public Nullable<double> No_5_NT { get; set; }
        public Nullable<double> Co_5_NT { get; set; }
        public Nullable<double> DuNo_5 { get; set; }
        public Nullable<double> DuCo_5 { get; set; }
        public Nullable<double> DuNT_5 { get; set; }
        public Nullable<double> No_6 { get; set; }
        public Nullable<double> Co_6 { get; set; }
        public Nullable<double> No_6_NT { get; set; }
        public Nullable<double> Co_6_NT { get; set; }
        public Nullable<double> DuNo_6 { get; set; }
        public Nullable<double> DuCo_6 { get; set; }
        public Nullable<double> DuNT_6 { get; set; }
        public Nullable<double> No_7 { get; set; }
        public Nullable<double> Co_7 { get; set; }
        public Nullable<double> No_7_NT { get; set; }
        public Nullable<double> Co_7_NT { get; set; }
        public Nullable<double> DuNo_7 { get; set; }
        public Nullable<double> DuCo_7 { get; set; }
        public Nullable<double> DuNT_7 { get; set; }
        public Nullable<double> No_8 { get; set; }
        public Nullable<double> Co_8 { get; set; }
        public Nullable<double> No_8_NT { get; set; }
        public Nullable<double> Co_8_NT { get; set; }
        public Nullable<double> DuNo_8 { get; set; }
        public Nullable<double> DuCo_8 { get; set; }
        public Nullable<double> DuNT_8 { get; set; }
        public Nullable<double> No_9 { get; set; }
        public Nullable<double> Co_9 { get; set; }
        public Nullable<double> No_9_NT { get; set; }
        public Nullable<double> Co_9_NT { get; set; }
        public Nullable<double> DuNo_9 { get; set; }
        public Nullable<double> DuCo_9 { get; set; }
        public Nullable<double> DuNT_9 { get; set; }
        public Nullable<double> No_10 { get; set; }
        public Nullable<double> Co_10 { get; set; }
        public Nullable<double> No_10_NT { get; set; }
        public Nullable<double> Co_10_NT { get; set; }
        public Nullable<double> DuNo_10 { get; set; }
        public Nullable<double> DuCo_10 { get; set; }
        public Nullable<double> DuNT_10 { get; set; }
        public Nullable<double> No_11 { get; set; }
        public Nullable<double> Co_11 { get; set; }
        public Nullable<double> No_11_NT { get; set; }
        public Nullable<double> Co_11_NT { get; set; }
        public Nullable<double> DuNo_11 { get; set; }
        public Nullable<double> DuCo_11 { get; set; }
        public Nullable<double> DuNT_11 { get; set; }
        public Nullable<double> No_12 { get; set; }
        public Nullable<double> Co_12 { get; set; }
        public Nullable<double> No_12_NT { get; set; }
        public Nullable<double> Co_12_NT { get; set; }
        public Nullable<double> DuNo_12 { get; set; }
        public Nullable<double> DuCo_12 { get; set; }
        public Nullable<double> DuNT_12 { get; set; }
        public Nullable<short> TK_ID { get; set; }
        public Nullable<short> TK_ID2 { get; set; }
        public Nullable<double> SoDuMax { get; set; }
        public Nullable<double> SoDuMin { get; set; }
        public Nullable<int> TKCha0 { get; set; }
        public Nullable<int> TKCha1 { get; set; }
        public Nullable<int> TKCha2 { get; set; }
        public Nullable<int> TKCha3 { get; set; }
        public Nullable<int> TKCha4 { get; set; }
        public Nullable<int> TKCha5 { get; set; }
        public Nullable<int> MaTC { get; set; }
        public Nullable<double> KC_N { get; set; }
        public Nullable<double> KC_C { get; set; }
        public Nullable<double> DuNo { get; set; }
        public Nullable<double> DuCo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<short> CapDuoi { get; set; }
        public string TenE { get; set; }
        public Nullable<int> TK_ID3 { get; set; }
        public string TenDA { get; set; }
        public string NhomDA { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<double> DuToan { get; set; }
        public Nullable<double> Von1 { get; set; }
        public Nullable<double> Von2 { get; set; }
        public Nullable<double> Von3 { get; set; }
        public Nullable<System.DateTime> NgayKC { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<double> PSNLK { get; set; }
        public Nullable<double> PSCLK { get; set; }
        public Nullable<double> PSNLK2005 { get; set; }
        public Nullable<double> PSCLK2005 { get; set; }
        public Nullable<double> PSNLK2006 { get; set; }
        public Nullable<double> PSCLK2006 { get; set; }
        public Nullable<double> PSNLK2008 { get; set; }
        public Nullable<double> PSCLK2008 { get; set; }
        public Nullable<double> PSNLK2009 { get; set; }
        public Nullable<double> PSCLK2009 { get; set; }
        public Nullable<double> PSNLK2010 { get; set; }
        public Nullable<double> PSCLK2010 { get; set; }
        public Nullable<double> PSNLK2011 { get; set; }
        public Nullable<double> PSCLK2011 { get; set; }
        public Nullable<double> PSNLK2012 { get; set; }
        public Nullable<double> PSCLK2012 { get; set; }
        public Nullable<double> PSNLK2013 { get; set; }
        public Nullable<double> PSCLK2013 { get; set; }
        public Nullable<double> PSNLK2014 { get; set; }
        public Nullable<double> PSCLK2014 { get; set; }
        public string THEMMOI { get; set; }
        public Nullable<double> PSNLK2018 { get; set; }
        public Nullable<double> PSCLK2018 { get; set; }
        public Nullable<double> PSNLK2019 { get; set; }
        public Nullable<double> PSCLK2019 { get; set; }
        public Nullable<double> PSNLK2020 { get; set; }
        public Nullable<double> PSCLK2020 { get; set; }
        public Nullable<double> PSNLK2021 { get; set; }
        public Nullable<double> PSCLK2021 { get; set; }
        public Nullable<double> PSNLK2022 { get; set; }
        public Nullable<double> PSCLK2022 { get; set; }
        public Nullable<double> PSNLK2023 { get; set; }
        public Nullable<double> PSCLK2023 { get; set; }
        public Nullable<double> PSNLK2025 { get; set; }
        public Nullable<double> PSCLK2025 { get; set; }
    }
}
