//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonP
    {
        public int MaSo { get; set; }
        public Nullable<short> Loai { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public string KyHieu { get; set; }
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayPH { get; set; }
        public string MatHang { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<short> TyLe { get; set; }
        public Nullable<short> HD { get; set; }
        public Nullable<short> KCT { get; set; }
        public Nullable<double> GiaTT { get; set; }
        public string HTTT { get; set; }
        public string MauSo { get; set; }
        public Nullable<short> HDBL { get; set; }
        public Nullable<short> NK { get; set; }
        public Nullable<short> TS { get; set; }
        public Nullable<short> DC { get; set; }
        public Nullable<double> TyGia { get; set; }
    }
}
