//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCChitiet
    {
        public int MaSo { get; set; }
        public Nullable<int> MaKC { get; set; }
        public Nullable<int> TK1 { get; set; }
        public Nullable<int> TK2 { get; set; }
    }
}
