//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int MaSo { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public string SoHieu { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string MST { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string TaiKhoan { get; set; }
        public string DaiDien { get; set; }
        public Nullable<double> DuMax { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaNT { get; set; }
        public string contact_id { get; set; }
    }
}
