//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemKe
    {
        public int MaSo { get; set; }
        public Nullable<int> MaSoKho { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> MaVatTu { get; set; }
        public Nullable<double> Luong_1 { get; set; }
        public Nullable<double> Tien_1 { get; set; }
        public Nullable<double> Luong_2 { get; set; }
        public Nullable<double> Tien_2 { get; set; }
        public Nullable<double> Luong_3 { get; set; }
        public Nullable<double> Tien_3 { get; set; }
        public Nullable<double> Luong_4 { get; set; }
        public Nullable<double> Tien_4 { get; set; }
        public Nullable<double> Luong_5 { get; set; }
        public Nullable<double> Tien_5 { get; set; }
        public Nullable<double> Luong_6 { get; set; }
        public Nullable<double> Tien_6 { get; set; }
        public Nullable<double> Luong_7 { get; set; }
        public Nullable<double> Tien_7 { get; set; }
        public Nullable<double> Luong_8 { get; set; }
        public Nullable<double> Tien_8 { get; set; }
        public Nullable<double> Luong_9 { get; set; }
        public Nullable<double> Tien_9 { get; set; }
        public Nullable<double> Luong_10 { get; set; }
        public Nullable<double> Tien_10 { get; set; }
        public Nullable<double> Luong_11 { get; set; }
        public Nullable<double> Tien_11 { get; set; }
        public Nullable<double> Tien_12 { get; set; }
        public Nullable<double> Luong_12 { get; set; }
    }
}
