//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQKD911
    {
        public Nullable<int> Ma { get; set; }
        public int MaSo { get; set; }
        public string Ten { get; set; }
        public string SHTKNo { get; set; }
        public string SHTKCo { get; set; }
        public Nullable<double> DauNam { get; set; }
        public Nullable<double> KyTruoc { get; set; }
        public Nullable<double> KyNay { get; set; }
        public Nullable<short> TongHop { get; set; }
        public Nullable<int> MaSoCha { get; set; }
        public string TenE { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<short> Cap { get; set; }
    }
}
