//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaiSuat
    {
        public int MaSo { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<double> LS { get; set; }
        public Nullable<int> MaKH { get; set; }
    }
}
