//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatablankEntities : DbContext
    {
        public DatablankEntities()
            : base("name=DatablankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoCP> BaoCaoCPs { get; set; }
        public virtual DbSet<BaoCaoCP2> BaoCaoCP2 { get; set; }
        public virtual DbSet<BARCODE> BARCODEs { get; set; }
        public virtual DbSet<BKNhomP> BKNhomPS { get; set; }
        public virtual DbSet<CDT> CDTS { get; set; }
        public virtual DbSet<cdts48> cdts48 { get; set; }
        public virtual DbSet<ChungTu2> ChungTu2 { get; set; }
        public virtual DbSet<ChungTuLQ> ChungTuLQs { get; set; }
        public virtual DbSet<ChungTuLQP> ChungTuLQPs { get; set; }
        public virtual DbSet<ChungTuP> ChungTuPs { get; set; }
        public virtual DbSet<CNDauNam> CNDauNams { get; set; }
        public virtual DbSet<CNDauNam2> CNDauNam2 { get; set; }
        public virtual DbSet<CPGVHD> CPGVHDs { get; set; }
        public virtual DbSet<CTGhiSo> CTGhiSoes { get; set; }
        public virtual DbSet<CTKetChuyen> CTKetChuyens { get; set; }
        public virtual DbSet<CTTaiSan> CTTaiSans { get; set; }
        public virtual DbSet<DCPTung> DCPTungs { get; set; }
        public virtual DbSet<DinhMuc> DinhMucs { get; set; }
        public virtual DbSet<DoituongCT> DoituongCTs { get; set; }
        public virtual DbSet<DTQLy> DTQLies { get; set; }
        public virtual DbSet<DVTVattu> DVTVattus { get; set; }
        public virtual DbSet<HeThongTK> HeThongTKs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoaDonP> HoaDonPs { get; set; }
        public virtual DbSet<KCChitiet> KCChitiets { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhoHang> KhoHangs { get; set; }
        public virtual DbSet<KiemKe> KiemKes { get; set; }
        public virtual DbSet<KiemKeN> KiemKeNs { get; set; }
        public virtual DbSet<KQKD911> KQKD911 { get; set; }
        public virtual DbSet<LaiSuat> LaiSuats { get; set; }
        public virtual DbSet<LoaiChungTu> LoaiChungTus { get; set; }
        public virtual DbSet<LoaiTaiSan> LoaiTaiSans { get; set; }
        public virtual DbSet<NguonNhapXuat> NguonNhapXuats { get; set; }
        public virtual DbSet<NguyenTe> NguyenTes { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanLoai154> PhanLoai154 { get; set; }
        public virtual DbSet<PhanLoaiKhachHang> PhanLoaiKhachHangs { get; set; }
        public virtual DbSet<PhanLoaiNhanVien> PhanLoaiNhanViens { get; set; }
        public virtual DbSet<PhanLoaiVattu> PhanLoaiVattus { get; set; }
        public virtual DbSet<PhieuNX> PhieuNXes { get; set; }
        public virtual DbSet<QuocGia> QuocGias { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<SHchungtu> SHchungtus { get; set; }
        public virtual DbSet<SoDuKhachHang> SoDuKhachHangs { get; set; }
        public virtual DbSet<tableHoadonvao> tableHoadonvaos { get; set; }
        public virtual DbSet<TaiSan> TaiSans { get; set; }
        public virtual DbSet<tbDinhdanhNganhang> tbDinhdanhNganhangs { get; set; }
        public virtual DbSet<tbDinhdanhtaikhoan> tbDinhdanhtaikhoans { get; set; }
        public virtual DbSet<tbFontsize> tbFontsizes { get; set; }
        public virtual DbSet<tbGetphieu> tbGetphieux { get; set; }
        public virtual DbSet<tbGhichuHT> tbGhichuHTs { get; set; }
        public virtual DbSet<tbHoadonThaythe> tbHoadonThaythes { get; set; }
        public virtual DbSet<tbimport> tbimports { get; set; }
        public virtual DbSet<tbimportdetail> tbimportdetails { get; set; }
        public virtual DbSet<tbMatdinhghichu> tbMatdinhghichus { get; set; }
        public virtual DbSet<tbNguyenLieuThanhPham> tbNguyenLieuThanhPhams { get; set; }
        public virtual DbSet<tbNhapkhonguyenlieu> tbNhapkhonguyenlieux { get; set; }
        public virtual DbSet<tbNhapkhotp> tbNhapkhotps { get; set; }
        public virtual DbSet<tbNhapkhotpChitiet> tbNhapkhotpChitiets { get; set; }
        public virtual DbSet<tbPL1> tbPL1 { get; set; }
        public virtual DbSet<tbPL2> tbPL2 { get; set; }
        public virtual DbSet<tbThongTinToKhai> tbThongTinToKhais { get; set; }
        public virtual DbSet<ThanhPham> ThanhPhams { get; set; }
        public virtual DbSet<ThongSo> ThongSoes { get; set; }
        public virtual DbSet<THUE> THUEs { get; set; }
        public virtual DbSet<TinhTrang> TinhTrangs { get; set; }
        public virtual DbSet<TonKho> TonKhoes { get; set; }
        public virtual DbSet<TP154> TP154 { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vattu> Vattus { get; set; }
        public virtual DbSet<VTDauNam> VTDauNams { get; set; }
        public virtual DbSet<DanhSachVatTu> DanhSachVatTus { get; set; }
        public virtual DbSet<ChungTu> ChungTus { get; set; }
    }
}
