//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiVattu
    {
        public int MaSo { get; set; }
        public string SoHieu { get; set; }
        public string TenPhanLoai { get; set; }
        public Nullable<short> VAT { get; set; }
        public Nullable<short> PLCon { get; set; }
        public Nullable<short> Cap { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<short> PLCha { get; set; }
        public string TKCo { get; set; }
        public string GhiChu { get; set; }
        public string TKNo { get; set; }
        public Nullable<double> MaPhanLoaiCu { get; set; }
    }
}
