//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNX
    {
        public int MaSo { get; set; }
        public string SoCT { get; set; }
        public string DienGiaiCT { get; set; }
        public string SoHieu { get; set; }
        public string DienGiai { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string Kho { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<short> TyLe { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> ThanhTien2 { get; set; }
        public Nullable<double> CK { get; set; }
    }
}
