//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QNhatky
    {
        public string KyHieu { get; set; }
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayPH { get; set; }
        public string MatHang { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string Ten { get; set; }
        public string MST { get; set; }
        public string SoHieu { get; set; }
        public Nullable<double> SoPS { get; set; }
        public string DiaChi { get; set; }
        public Nullable<short> TyLe { get; set; }
        public string HTTT { get; set; }
        public string MauSo { get; set; }
        public Nullable<int> MaCT { get; set; }
        public int MaSo { get; set; }
        public Nullable<short> KCT { get; set; }
    }
}
