//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTheKho
    {
        public Nullable<int> MaNT { get; set; }
        public string KyHieu { get; set; }
        public int DKNo { get; set; }
        public int DKCo { get; set; }
        public Nullable<double> DKNT { get; set; }
        public int CKNo { get; set; }
        public int CKCo { get; set; }
        public Nullable<double> CKNT { get; set; }
    }
}
