//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socai
    {
        public string SoHieuTK { get; set; }
        public int NoDk { get; set; }
        public int Kieu { get; set; }
        public string TenTk { get; set; }
        public int NoLK { get; set; }
        public int CoLK { get; set; }
    }
}
