//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoDuKhachHang
    {
        public int MaSo { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<double> DuNo_0 { get; set; }
        public Nullable<double> DuCo_0 { get; set; }
        public Nullable<double> DuNT_0 { get; set; }
        public Nullable<double> No_1 { get; set; }
        public Nullable<double> Co_1 { get; set; }
        public Nullable<double> No_1_NT { get; set; }
        public Nullable<double> Co_1_NT { get; set; }
        public Nullable<double> DuNo_1 { get; set; }
        public Nullable<double> DuCo_1 { get; set; }
        public Nullable<double> DuNT_1 { get; set; }
        public Nullable<double> No_2 { get; set; }
        public Nullable<double> Co_2 { get; set; }
        public Nullable<double> No_2_NT { get; set; }
        public Nullable<double> Co_2_NT { get; set; }
        public Nullable<double> DuNo_2 { get; set; }
        public Nullable<double> DuCo_2 { get; set; }
        public Nullable<double> DuNT_2 { get; set; }
        public Nullable<double> No_3 { get; set; }
        public Nullable<double> Co_3 { get; set; }
        public Nullable<double> No_3_NT { get; set; }
        public Nullable<double> Co_3_NT { get; set; }
        public Nullable<double> DuNo_3 { get; set; }
        public Nullable<double> DuCo_3 { get; set; }
        public Nullable<double> DuNT_3 { get; set; }
        public Nullable<double> No_4 { get; set; }
        public Nullable<double> Co_4 { get; set; }
        public Nullable<double> No_4_NT { get; set; }
        public Nullable<double> Co_4_NT { get; set; }
        public Nullable<double> DuNo_4 { get; set; }
        public Nullable<double> DuCo_4 { get; set; }
        public Nullable<double> DuNT_4 { get; set; }
        public Nullable<double> No_5 { get; set; }
        public Nullable<double> Co_5 { get; set; }
        public Nullable<double> No_5_NT { get; set; }
        public Nullable<double> Co_5_NT { get; set; }
        public Nullable<double> DuNo_5 { get; set; }
        public Nullable<double> DuCo_5 { get; set; }
        public Nullable<double> DuNT_5 { get; set; }
        public Nullable<double> No_6 { get; set; }
        public Nullable<double> Co_6 { get; set; }
        public Nullable<double> No_6_NT { get; set; }
        public Nullable<double> Co_6_NT { get; set; }
        public Nullable<double> DuNo_6 { get; set; }
        public Nullable<double> DuCo_6 { get; set; }
        public Nullable<double> DuNT_6 { get; set; }
        public Nullable<double> No_7 { get; set; }
        public Nullable<double> Co_7 { get; set; }
        public Nullable<double> No_7_NT { get; set; }
        public Nullable<double> Co_7_NT { get; set; }
        public Nullable<double> DuNo_7 { get; set; }
        public Nullable<double> DuCo_7 { get; set; }
        public Nullable<double> DuNT_7 { get; set; }
        public Nullable<double> No_8 { get; set; }
        public Nullable<double> Co_8 { get; set; }
        public Nullable<double> No_8_NT { get; set; }
        public Nullable<double> Co_8_NT { get; set; }
        public Nullable<double> DuNo_8 { get; set; }
        public Nullable<double> DuCo_8 { get; set; }
        public Nullable<double> DuNT_8 { get; set; }
        public Nullable<double> No_9 { get; set; }
        public Nullable<double> Co_9 { get; set; }
        public Nullable<double> No_9_NT { get; set; }
        public Nullable<double> Co_9_NT { get; set; }
        public Nullable<double> DuNo_9 { get; set; }
        public Nullable<double> DuCo_9 { get; set; }
        public Nullable<double> DuNT_9 { get; set; }
        public Nullable<double> No_10 { get; set; }
        public Nullable<double> Co_10 { get; set; }
        public Nullable<double> No_10_NT { get; set; }
        public Nullable<double> Co_10_NT { get; set; }
        public Nullable<double> DuNo_10 { get; set; }
        public Nullable<double> DuCo_10 { get; set; }
        public Nullable<double> DuNT_10 { get; set; }
        public Nullable<double> No_11 { get; set; }
        public Nullable<double> Co_11 { get; set; }
        public Nullable<double> No_11_NT { get; set; }
        public Nullable<double> Co_11_NT { get; set; }
        public Nullable<double> DuNo_11 { get; set; }
        public Nullable<double> DuCo_11 { get; set; }
        public Nullable<double> DuNT_11 { get; set; }
        public Nullable<double> No_12 { get; set; }
        public Nullable<double> Co_12 { get; set; }
        public Nullable<double> No_12_NT { get; set; }
        public Nullable<double> Co_12_NT { get; set; }
        public Nullable<double> DuNo_12 { get; set; }
        public Nullable<double> DuCo_12 { get; set; }
        public Nullable<double> DuNT_12 { get; set; }
    }
}
