//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableHoadonvao
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string SoHieu { get; set; }
        public string TenKH { get; set; }
        public string MaSoHH { get; set; }
        public string TenHH { get; set; }
        public Nullable<double> SL { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> Hinhthuc { get; set; }
        public string TKNo { get; set; }
        public string TKCo { get; set; }
        public string TKThue { get; set; }
    }
}
