//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiSan
    {
        public int MaSo { get; set; }
        public string SoHieu { get; set; }
        public string Ten { get; set; }
        public string NangLuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaNuoc { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<short> ThangTang { get; set; }
        public Nullable<short> ThangGiam { get; set; }
        public Nullable<short> NamSX { get; set; }
        public Nullable<short> NamSD { get; set; }
        public Nullable<short> NamKH { get; set; }
        public string SHCT { get; set; }
        public Nullable<System.DateTime> NCT { get; set; }
        public Nullable<double> taisanIdCu { get; set; }
    }
}
