//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDinhdanhNganhang
    {
        public int ID { get; set; }
        public string Noidung { get; set; }
        public string TK { get; set; }
        public string SoHieu { get; set; }
        public string TK2 { get; set; }
    }
}
