//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDinhdanhtaikhoan
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string KeyValue { get; set; }
        public string TKNo { get; set; }
        public string TKCo { get; set; }
        public string TKThue { get; set; }
        public string Uutien { get; set; }
        public string Loai { get; set; }
        public string IsChecked { get; set; }
    }
}
