//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFontsize
    {
        public int ID { get; set; }
        public string MemnuFont { get; set; }
        public Nullable<double> MenuSize { get; set; }
        public Nullable<double> MenuBold { get; set; }
        public string ControlvniFont { get; set; }
        public Nullable<double> ControlvniSize { get; set; }
        public string ControluniFont { get; set; }
        public Nullable<double> ControluniSize { get; set; }
    }
}
