//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGetphieu
    {
        public int ID { get; set; }
        public string MaCT { get; set; }
        public string TenNM { get; set; }
        public string TenCty { get; set; }
        public string DiaChi { get; set; }
        public string HTTT { get; set; }
        public string CCCD { get; set; }
        public string TyLe { get; set; }
    }
}
