//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHoadonThaythe
    {
        public int ID { get; set; }
        public string SoHD { get; set; }
        public string KHHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> HD1 { get; set; }
        public Nullable<double> HD2 { get; set; }
        public string Noidung { get; set; }
    }
}
