//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbimportdetail
    {
        public int ID { get; set; }
        public string ParentId { get; set; }
        public string SoHieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string DVT { get; set; }
        public string Ten { get; set; }
        public string MaCT { get; set; }
        public string TKNo { get; set; }
        public string TKCo { get; set; }
        public Nullable<decimal> TTien { get; set; }
        public string Percent { get; set; }
        public Nullable<double> Tchat { get; set; }
        public Nullable<double> IsMacdinh { get; set; }
        public Nullable<double> SoPSGoc { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<decimal> TTien_New { get; set; }
    }
}
