//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbimport
    {
        public int ID { get; set; }
        public string SHDon { get; set; }
        public string KHHDon { get; set; }
        public Nullable<System.DateTime> NLap { get; set; }
        public string Ten { get; set; }
        public string Noidung { get; set; }
        public string TKCo { get; set; }
        public string TKNo { get; set; }
        public string TkThue { get; set; }
        public string Mst { get; set; }
        public Nullable<double> Status { get; set; }
        public string Ngaytao { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> Vat { get; set; }
        public string SohieuTP { get; set; }
        public Nullable<double> TVat3 { get; set; }
        public Nullable<double> TVat2 { get; set; }
        public Nullable<double> TVat { get; set; }
        public string Vat3 { get; set; }
        public string Vat2 { get; set; }
        public string InvoiceType { get; set; }
        public string IsHaschild { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public Nullable<double> TPhi { get; set; }
        public Nullable<double> TgTCThue { get; set; }
        public Nullable<double> TgTThue { get; set; }
        public Nullable<double> TgTCThue1 { get; set; }
        public Nullable<double> TgTCThue2 { get; set; }
        public Nullable<double> TgTCThue3 { get; set; }
        public string Macdinhstatus { get; set; }
        public string Khmshdon { get; set; }
        public string idhoadon { get; set; }
        public Nullable<double> IsImport { get; set; }
        public string hdon { get; set; }
        public Nullable<double> Khautruthue { get; set; }
    }
}
