//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNguyenLieuThanhPham
    {
        public int ID { get; set; }
        public string TPSoHieu { get; set; }
        public Nullable<double> IDNguyenLieu { get; set; }
        public string SoHieuNguyenLieu { get; set; }
        public Nullable<double> TiLe { get; set; }
        public Nullable<double> stt { get; set; }
    }
}
