//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNhapkhonguyenlieu
    {
        public int ID { get; set; }
        public Nullable<double> ParentId { get; set; }
        public Nullable<double> TTien { get; set; }
        public Nullable<double> SL { get; set; }
        public string SoHieuTP { get; set; }
        public string SoHieu { get; set; }
    }
}
