//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNhapkhotp
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string SoHieu { get; set; }
        public string Ghichu { get; set; }
        public string Status { get; set; }
        public string Ghichu2 { get; set; }
        public string SoHieu2 { get; set; }
    }
}
