//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPL2
    {
        public int ID { get; set; }
        public string TenHH { get; set; }
        public Nullable<double> GT1 { get; set; }
        public Nullable<double> GT2 { get; set; }
    }
}
