//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbThongTinToKhai
    {
        public int ID { get; set; }
        public Nullable<double> Quy1 { get; set; }
        public Nullable<double> Quy2 { get; set; }
        public Nullable<double> Quy3 { get; set; }
        public Nullable<double> Quy4 { get; set; }
        public Nullable<double> T1 { get; set; }
        public Nullable<double> T2 { get; set; }
        public Nullable<double> T3 { get; set; }
        public Nullable<double> T4 { get; set; }
        public Nullable<double> T5 { get; set; }
        public Nullable<double> T6 { get; set; }
        public Nullable<double> T7 { get; set; }
        public Nullable<double> T8 { get; set; }
        public Nullable<double> T9 { get; set; }
        public Nullable<double> T10 { get; set; }
        public Nullable<double> T11 { get; set; }
        public Nullable<double> T12 { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<short> Nam { get; set; }
        public string k1 { get; set; }
        public string k2 { get; set; }
        public string k3 { get; set; }
        public string k4 { get; set; }
        public string k5 { get; set; }
        public string k6 { get; set; }
        public string k7 { get; set; }
        public string k8 { get; set; }
        public string k9 { get; set; }
        public string k10 { get; set; }
        public string k11 { get; set; }
        public string k12 { get; set; }
        public string xml1 { get; set; }
        public string xml2 { get; set; }
        public string xml3 { get; set; }
        public string xml4 { get; set; }
        public string xml5 { get; set; }
        public string xml6 { get; set; }
        public string xml7 { get; set; }
        public string xml8 { get; set; }
        public string xml9 { get; set; }
        public string xml10 { get; set; }
        public string xml11 { get; set; }
        public string xml12 { get; set; }
    }
}
