//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPham
    {
        public int MaSo { get; set; }
        public Nullable<int> MaCT { get; set; }
        public string SoHieu { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> MaKhoTP { get; set; }
        public Nullable<int> MaKhoNVL { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> MaTP { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<int> MaTKCP { get; set; }
        public Nullable<int> MaTKNC { get; set; }
        public Nullable<int> MaTKSX { get; set; }
        public Nullable<double> CPNVL { get; set; }
        public Nullable<double> CPNC { get; set; }
        public Nullable<double> CPSXC { get; set; }
        public Nullable<double> CPBH { get; set; }
        public Nullable<double> CPQL { get; set; }
        public Nullable<int> MaTKKH { get; set; }
        public Nullable<double> CPKH { get; set; }
        public Nullable<int> Ma154 { get; set; }
        public Nullable<double> GiaThanh { get; set; }
        public Nullable<short> XK { get; set; }
        public Nullable<double> CPTC { get; set; }
    }
}
