//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSo
    {
        public int MaSo { get; set; }
        public Nullable<int> MaTS { get; set; }
        public Nullable<short> Thang { get; set; }
        public Nullable<double> KH_NS { get; set; }
        public Nullable<double> KH_TBS { get; set; }
        public Nullable<double> KH_CNK { get; set; }
        public Nullable<double> KH_TD { get; set; }
        public Nullable<double> NG_NS { get; set; }
        public Nullable<double> NG_TBS { get; set; }
        public Nullable<double> NG_CNK { get; set; }
        public Nullable<double> NG_TD { get; set; }
        public Nullable<double> CL_NS { get; set; }
        public Nullable<double> CL_TBS { get; set; }
        public Nullable<double> CL_CNK { get; set; }
        public Nullable<double> CL_TD { get; set; }
        public Nullable<int> MaDTQL { get; set; }
        public Nullable<int> MaDTSD { get; set; }
        public Nullable<int> MaTTSD { get; set; }
        public Nullable<double> taisanIdCu { get; set; }
    }
}
