//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUE
    {
        public Nullable<int> Ma { get; set; }
        public int MaSo { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> MaTk { get; set; }
        public Nullable<double> KyTruocSang { get; set; }
        public Nullable<double> KyNay { get; set; }
        public Nullable<double> LuyKePN { get; set; }
        public Nullable<double> DaNop { get; set; }
        public Nullable<double> LuyKeDN { get; set; }
        public Nullable<short> TongHop { get; set; }
        public string DienGiaiE { get; set; }
        public Nullable<double> DaHoan { get; set; }
        public Nullable<double> MienGiam { get; set; }
    }
}
