//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP154
    {
        public int MaSo { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public string SoHieu { get; set; }
        public string TenVattu { get; set; }
        public string DonVi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> DK { get; set; }
        public Nullable<double> DK1 { get; set; }
        public Nullable<double> CK1 { get; set; }
        public Nullable<double> CPNVL { get; set; }
        public Nullable<double> CPNC { get; set; }
        public Nullable<double> CPM { get; set; }
        public Nullable<double> CPKH_1 { get; set; }
        public Nullable<double> CPSXC_1 { get; set; }
        public Nullable<double> CPKH_2 { get; set; }
        public Nullable<double> CPSXC_2 { get; set; }
        public Nullable<double> CPKH_3 { get; set; }
        public Nullable<double> CPSXC_3 { get; set; }
        public Nullable<double> CPKH_4 { get; set; }
        public Nullable<double> CPSXC_4 { get; set; }
        public Nullable<double> CPKH_5 { get; set; }
        public Nullable<double> CPSXC_5 { get; set; }
        public Nullable<double> CPKH_6 { get; set; }
        public Nullable<double> CPSXC_6 { get; set; }
        public Nullable<double> CPKH_7 { get; set; }
        public Nullable<double> CPSXC_7 { get; set; }
        public Nullable<double> CPKH_8 { get; set; }
        public Nullable<double> CPSXC_8 { get; set; }
        public Nullable<double> CPKH_9 { get; set; }
        public Nullable<double> CPSXC_9 { get; set; }
        public Nullable<double> CPKH_10 { get; set; }
        public Nullable<double> CPSXC_10 { get; set; }
        public Nullable<double> CPKH_11 { get; set; }
        public Nullable<double> CPSXC_11 { get; set; }
        public Nullable<double> CPKH_12 { get; set; }
        public Nullable<double> CPSXC_12 { get; set; }
        public Nullable<double> CPBH1 { get; set; }
        public Nullable<double> CPQL1 { get; set; }
        public Nullable<double> CPBHTT1 { get; set; }
        public Nullable<double> CPQLTT1 { get; set; }
        public Nullable<double> CPSXCTT1 { get; set; }
        public Nullable<double> CPNVLPB1 { get; set; }
        public Nullable<double> CPNCPB1 { get; set; }
        public Nullable<double> CPMPB1 { get; set; }
        public Nullable<double> CPBH2 { get; set; }
        public Nullable<double> CPQL2 { get; set; }
        public Nullable<double> CPBHTT2 { get; set; }
        public Nullable<double> CPQLTT2 { get; set; }
        public Nullable<double> CPSXCTT2 { get; set; }
        public Nullable<double> CPNVLPB2 { get; set; }
        public Nullable<double> CPNCPB2 { get; set; }
        public Nullable<double> CPMPB2 { get; set; }
        public Nullable<double> CPBH3 { get; set; }
        public Nullable<double> CPQL3 { get; set; }
        public Nullable<double> CPBHTT3 { get; set; }
        public Nullable<double> CPQLTT3 { get; set; }
        public Nullable<double> CPSXCTT3 { get; set; }
        public Nullable<double> CPNVLPB3 { get; set; }
        public Nullable<double> CPNCPB3 { get; set; }
        public Nullable<double> CPMPB3 { get; set; }
        public Nullable<double> CPBH4 { get; set; }
        public Nullable<double> CPQL4 { get; set; }
        public Nullable<double> CPBHTT4 { get; set; }
        public Nullable<double> CPQLTT4 { get; set; }
        public Nullable<double> CPSXCTT4 { get; set; }
        public Nullable<double> CPNVLPB4 { get; set; }
        public Nullable<double> CPNCPB4 { get; set; }
        public Nullable<double> CPMPB4 { get; set; }
        public Nullable<double> CPBH5 { get; set; }
        public Nullable<double> CPQL5 { get; set; }
        public Nullable<double> CPBHTT5 { get; set; }
        public Nullable<double> CPQLTT5 { get; set; }
        public Nullable<double> CPSXCTT5 { get; set; }
        public Nullable<double> CPNVLPB5 { get; set; }
        public Nullable<double> CPNCPB5 { get; set; }
        public Nullable<double> CPMPB5 { get; set; }
        public Nullable<double> CPBH6 { get; set; }
        public Nullable<double> CPQL6 { get; set; }
        public Nullable<double> CPBHTT6 { get; set; }
        public Nullable<double> CPQLTT6 { get; set; }
        public Nullable<double> CPSXCTT6 { get; set; }
        public Nullable<double> CPNVLPB6 { get; set; }
        public Nullable<double> CPNCPB6 { get; set; }
        public Nullable<double> CPMPB6 { get; set; }
        public Nullable<double> CPBH7 { get; set; }
        public Nullable<double> CPQL7 { get; set; }
        public Nullable<double> CPBHTT7 { get; set; }
        public Nullable<double> CPQLTT7 { get; set; }
        public Nullable<double> CPSXCTT7 { get; set; }
        public Nullable<double> CPNVLPB7 { get; set; }
        public Nullable<double> CPNCPB7 { get; set; }
        public Nullable<double> CPMPB7 { get; set; }
        public Nullable<double> CPBH8 { get; set; }
        public Nullable<double> CPQL8 { get; set; }
        public Nullable<double> CPBHTT8 { get; set; }
        public Nullable<double> CPQLTT8 { get; set; }
        public Nullable<double> CPSXCTT8 { get; set; }
        public Nullable<double> CPNVLPB8 { get; set; }
        public Nullable<double> CPNCPB8 { get; set; }
        public Nullable<double> CPMPB8 { get; set; }
        public Nullable<double> CPBH9 { get; set; }
        public Nullable<double> CPQL9 { get; set; }
        public Nullable<double> CPBHTT9 { get; set; }
        public Nullable<double> CPQLTT9 { get; set; }
        public Nullable<double> CPSXCTT9 { get; set; }
        public Nullable<double> CPNVLPB9 { get; set; }
        public Nullable<double> CPNCPB9 { get; set; }
        public Nullable<double> CPMPB9 { get; set; }
        public Nullable<double> CPBH10 { get; set; }
        public Nullable<double> CPQL10 { get; set; }
        public Nullable<double> CPBHTT10 { get; set; }
        public Nullable<double> CPQLTT10 { get; set; }
        public Nullable<double> CPSXCTT10 { get; set; }
        public Nullable<double> CPNVLPB10 { get; set; }
        public Nullable<double> CPNCPB10 { get; set; }
        public Nullable<double> CPMPB10 { get; set; }
        public Nullable<double> CPBH11 { get; set; }
        public Nullable<double> CPQL11 { get; set; }
        public Nullable<double> CPBHTT11 { get; set; }
        public Nullable<double> CPQLTT11 { get; set; }
        public Nullable<double> CPSXCTT11 { get; set; }
        public Nullable<double> CPNVLPB11 { get; set; }
        public Nullable<double> CPNCPB11 { get; set; }
        public Nullable<double> CPMPB11 { get; set; }
        public Nullable<double> CPBH12 { get; set; }
        public Nullable<double> CPQL12 { get; set; }
        public Nullable<double> CPBHTT12 { get; set; }
        public Nullable<double> CPQLTT12 { get; set; }
        public Nullable<double> CPSXCTT12 { get; set; }
        public Nullable<double> CPNVLPB12 { get; set; }
        public Nullable<double> CPNCPB12 { get; set; }
        public Nullable<double> CPMPB12 { get; set; }
        public Nullable<double> DT { get; set; }
        public Nullable<double> CPTC1 { get; set; }
        public Nullable<double> CPTCTT1 { get; set; }
        public Nullable<double> CPTC2 { get; set; }
        public Nullable<double> CPTCTT2 { get; set; }
        public Nullable<double> CPTC3 { get; set; }
        public Nullable<double> CPTCTT3 { get; set; }
        public Nullable<double> CPTC4 { get; set; }
        public Nullable<double> CPTCTT4 { get; set; }
        public Nullable<double> CPTC5 { get; set; }
        public Nullable<double> CPTCTT5 { get; set; }
        public Nullable<double> CPTC6 { get; set; }
        public Nullable<double> CPTCTT6 { get; set; }
        public Nullable<double> CPTC7 { get; set; }
        public Nullable<double> CPTCTT7 { get; set; }
        public Nullable<double> CPTC8 { get; set; }
        public Nullable<double> CPTCTT8 { get; set; }
        public Nullable<double> CPTC9 { get; set; }
        public Nullable<double> CPTCTT9 { get; set; }
        public Nullable<double> CPTC10 { get; set; }
        public Nullable<double> CPTCTT10 { get; set; }
        public Nullable<double> CPTC11 { get; set; }
        public Nullable<double> CPTCTT11 { get; set; }
        public Nullable<double> CPTC12 { get; set; }
        public Nullable<double> CPTCTT12 { get; set; }
        public Nullable<double> CPTC { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<short> KPB { get; set; }
        public Nullable<double> SanLuong { get; set; }
    }
}
