//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int MaSo { get; set; }
        public string TenNSD { get; set; }
        public Nullable<int> Psw { get; set; }
        public Nullable<short> UserRight { get; set; }
        public Nullable<int> VT { get; set; }
        public Nullable<short> TS { get; set; }
        public Nullable<short> HDV { get; set; }
        public string WS { get; set; }
        public Nullable<double> IsReister { get; set; }
        public string MacAddress { get; set; }
    }
}
