//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vattu
    {
        public int MaSo { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public string SoHieu { get; set; }
        public string TenVattu { get; set; }
        public string DonVi { get; set; }
        public Nullable<double> TonMin { get; set; }
        public Nullable<double> TonMax { get; set; }
        public Nullable<double> GiaDuPhong { get; set; }
        public Nullable<double> GiaHT { get; set; }
        public Nullable<short> dvt2 { get; set; }
        public string DonVi2 { get; set; }
        public Nullable<float> TyLeQD { get; set; }
        public string GhiChu { get; set; }
        public Nullable<short> VAT { get; set; }
        public Nullable<double> GiaBan1 { get; set; }
        public Nullable<double> GiaBan2 { get; set; }
        public Nullable<double> GiaBan3 { get; set; }
        public Nullable<double> CK { get; set; }
        public Nullable<double> ThueNK { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> T { get; set; }
        public string TenVattu2 { get; set; }
        public string PTGB { get; set; }
        public string TendoName { get; set; }
        public string TendoSku { get; set; }
        public string TendoUom { get; set; }
        public string TendoId { get; set; }
        public Nullable<double> TendoPrice { get; set; }
        public Nullable<double> TendokhoInventory { get; set; }
        public Nullable<double> TendoQuality { get; set; }
        public string TendoSkuId { get; set; }
    }
}
