//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaovietTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTDauNam
    {
        public int MaSo { get; set; }
        public Nullable<int> MaSoKho { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> MaVattu { get; set; }
        public Nullable<double> Tien_0 { get; set; }
        public Nullable<double> Luong_0 { get; set; }
        public Nullable<double> SoXuat { get; set; }
    }
}
